[profile.default]
via_ir = true
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"


remappings = [
    "@openzeppelin=lib/openzeppelin-contracts",
    "@chainlink=lib/chainlink",
]
[fuzz]
fail_on_revert = false

runs = 256
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
